### ISSUE TITLE
Error while computing transitive closure

### ISSUE THREAD

**Issue by alidabir** [DarkDNA/bazel-gopath#1]
Getting the following error:
`ERROR: Evaluation of query "deps(kind('_?go_.*|proto_compile rule', //...))" failed: errors were encountered while computing transitive closure` while running `bazel-gopath -workspace $PWD` and none of the protos get built. That appears to be [this line](https://github.com/DarkDNA/bazel-gopath/blob/f83ae8d403d0c826335a5edf4bbd1f7b0cf176e4/main.go#L55). Any ideas?

**Comment by AmandaCameron** [comment]
I'm guessing something is invalid in your bazel workspace (invalid BUILD file or similar) -- that command is a shell-out to bazel, to get a list of the go_* rules your workspace defines.

What version of bazel are you using, I've only tested recently against bazel 0.10.0

**Comment by alidabir** [comment]
Thanks for the reply. Here's my bazel version output:
Build label: 0.8.1-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 5 19:33:07 2017 (1512502387)
Build timestamp: 1512502387
Build timestamp as int: 1512502387

I upgraded to Build label: 0.11.1-homebrew but am still getting the same error.

**Comment by AmandaCameron** [comment]
Do you get the same error if you run `bazel query //...`?

**Comment by alidabir** [comment]
No, I get a directory listing.

**Comment by AmandaCameron** [comment]
I'm not sure then, sorry. You can try and run the query directly with `bazel query "deps(kind('_?go_.*|proto_compile rule', //...))"` and see if it outputs anything useful with that, but it sounds a lot like there's something in your workspace that bazel doesn't like, or you're missing a dependency or similar. If the project can build using bazel, then it's def. a bug in `bazel-gopath`, but I don't think that's the case here.

**Comment by alidabir** [comment]
The project actually builds using bazel. It should be something else.
When I manually run the command you mentioned I get errors:
```
ERROR: /private/var/tmp/_bazel_XXX/2c0a8c662162eefb40a61715a529d743/external/com_github_shirou_gopsutil/internal/common/BUILD.bazel:3:1: no such package '@com_github_stackexchange_wmi//': The repository could not be resolved and referenced by '@com_github_shirou_gopsutil//internal/common:go_default_library'
ERROR: /private/var/tmp/_bazel_XXX/2c0a8c662162eefb40a61715a529d743/external/com_github_shirou_gopsutil/cpu/BUILD.bazel:3:1: no such package '@com_github_stackexchange_wmi//': The repository could not be resolved and referenced by '@com_github_shirou_gopsutil//cpu:go_default_library'
ERROR: /private/var/tmp/_bazel_XXX/2c0a8c662162eefb40a61715a529d743/external/com_github_spf13_cobra/BUILD.bazel:3:1: no such package '@com_github_inconshreveable_mousetrap//': The repository could not be resolved and referenced by '@com_github_spf13_cobra//:go_default_library'
ERROR: /private/var/tmp/_bazel_XXX/2c0a8c662162eefb40a61715a529d743/external/com_github_shirou_gopsutil/cpu/BUILD.bazel:3:1: no such package '@com_github_stackexchange_wmi//': The repository could not be resolved and referenced by '@com_github_shirou_gopsutil//cpu:go_default_library'
ERROR: Evaluation of query "deps(kind('_?go_.*|proto_compile rule', //...))" failed: errors were encountered while computing transitive closure
```

**Comment by AmandaCameron** [comment]
Does the gopath get properly built? It'll be in `$workspace/.gopath` by default. I'm guessing those errors are just missing dependencies for parts of the libraries you don't use.

**Comment by alidabir** [comment]
A .gopath directory gets built in the project. It contains everything except protos.

**Comment by AmandaCameron** [comment]
What are you using to generate the protobuf .go files? I've been using the [rules_protobuf](https://github.com/pubref/rules_protobuf) rules, so I might not be handling the go_rule protobufs properly.

I'm open to a PR to fix it to work with those, but I have little interest in working on it myself, as we can't use the rules_go protobuf rules in our own code.

**Comment by alidabir** [comment]
I too am using rules_protobuf to build my project and it builds all the protobufs. Strange that bazel-gopath can't build those. I'm very new to this whole world of bazel and am kind of clueless. I think we should just leave it at that for now. Could be something very specific to my project configuration. Thanks for the help anyways :)

**Comment by AmandaCameron** [comment]
bazel-gopath doesn't do any building itself. It just talks to bazel to find out all the files, and builds a symlink-based gopath for use with other go tools such as gocode and the various source hopping things.

For protobuf stuff you will need to run the build once so that the source files get generated. Before doing that there will be the symlinks in the .gopath, but they will point to invalid files, which rules_protobuf will fill out after it's run.

It's also possible rules_protobuf has changed, as we've not updated that in our bazel for a bit, We're currently using the following rule in our WORKSPACE:

```python
git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf.git",
    commit = "d5d5a8e30b81599e25f1ff54ea870ab0194b96df", # https://github.com/pubref/rules_protobuf/pull/172 @ 2018-02-13
)
```

I'll try and find some time tomorrow to dig into it and make sure nothing needs tweaking for newer versions of rules_protobuf

**Comment by AmandaCameron** [comment]
Appologies, It was a bug in bazel-gopath after all. Sorry for the confusion, I was apparently running an older version of the `bazel-gopath` binary locally, so I didn't notice the bug that sneaked it's way in.
